/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AlertId = IDL.Text;
export const Timestamp = IDL.Int;
export const CreateAlertArgs = IDL.Record({
  'id' : AlertId,
  'title' : IDL.Text,
  'source' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Timestamp,
  'severity' : IDL.Text,
});
export const IncidentId = IDL.Text;
export const AffectedSystem = IDL.Record({
  'criticality' : IDL.Text,
  'compromiseDate' : IDL.Text,
  'detectionMethod' : IDL.Text,
  'systemName' : IDL.Text,
  'systemType' : IDL.Text,
});
export const CreateIncidentArgs = IDL.Record({
  'id' : IncidentId,
  'status' : IDL.Text,
  'userAccounts' : IDL.Text,
  'hostnames' : IDL.Text,
  'businessImpact' : IDL.Text,
  'type' : IDL.Text,
  'dataExposed' : IDL.Text,
  'systems' : IDL.Text,
  'timestamp' : Timestamp,
  'affectedSystems' : IDL.Vec(AffectedSystem),
  'severity' : IDL.Text,
  'usersAffected' : IDL.Nat,
  'qrCode' : IDL.Opt(IDL.Text),
});
export const IncidentView = IDL.Record({
  'id' : IncidentId,
  'status' : IDL.Text,
  'userAccounts' : IDL.Text,
  'hostnames' : IDL.Text,
  'businessImpact' : IDL.Text,
  'type' : IDL.Text,
  'dataExposed' : IDL.Text,
  'systems' : IDL.Text,
  'timestamp' : Timestamp,
  'affectedSystems' : IDL.Vec(AffectedSystem),
  'severity' : IDL.Text,
  'usersAffected' : IDL.Nat,
  'qrCode' : IDL.Opt(IDL.Text),
});
export const Stats = IDL.Record({
  'avgResponseMinutes' : IDL.Float64,
  'incidentsThisWeek' : IDL.Nat,
  'incidentsToday' : IDL.Nat,
  'criticalAlertCount' : IDL.Nat,
});
export const AlertView = IDL.Record({
  'id' : AlertId,
  'title' : IDL.Text,
  'incidentId' : IDL.Opt(IncidentId),
  'source' : IDL.Text,
  'falsePositive' : IDL.Bool,
  'description' : IDL.Text,
  'acknowledged' : IDL.Bool,
  'timestamp' : Timestamp,
  'severity' : IDL.Text,
});
export const IocId = IDL.Text;
export const IOC = IDL.Record({
  'value' : IDL.Text,
  'addedAt' : Timestamp,
  'iocType' : IDL.Text,
  'severity' : IDL.Text,
  'iocId' : IocId,
});
export const FeedId = IDL.Text;
export const ThreatFeed = IDL.Record({
  'title' : IDL.Text,
  'source' : IDL.Text,
  'feedId' : FeedId,
  'publishedAt' : Timestamp,
  'description' : IDL.Text,
  'severity' : IDL.Text,
});

export const idlService = IDL.Service({
  'acknowledgeAlert' : IDL.Func([AlertId], [IDL.Bool], []),
  'createAlert' : IDL.Func([CreateAlertArgs], [], []),
  'createIncident' : IDL.Func([CreateIncidentArgs], [], []),
  'deleteIncident' : IDL.Func([IncidentId], [IDL.Bool], []),
  'getIncident' : IDL.Func([IncidentId], [IDL.Opt(IncidentView)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'linkAlertToIncident' : IDL.Func([AlertId, IncidentId], [IDL.Bool], []),
  'listAlerts' : IDL.Func([], [IDL.Vec(AlertView)], ['query']),
  'listIOCs' : IDL.Func([], [IDL.Vec(IOC)], ['query']),
  'listIncidents' : IDL.Func([], [IDL.Vec(IncidentView)], ['query']),
  'listThreatFeeds' : IDL.Func([], [IDL.Vec(ThreatFeed)], ['query']),
  'markAlertFalsePositive' : IDL.Func([AlertId], [IDL.Bool], []),
  'updateIncidentQrCode' : IDL.Func([IncidentId, IDL.Text], [IDL.Bool], []),
  'updateIncidentStatus' : IDL.Func([IncidentId, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AlertId = IDL.Text;
  const Timestamp = IDL.Int;
  const CreateAlertArgs = IDL.Record({
    'id' : AlertId,
    'title' : IDL.Text,
    'source' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Timestamp,
    'severity' : IDL.Text,
  });
  const IncidentId = IDL.Text;
  const AffectedSystem = IDL.Record({
    'criticality' : IDL.Text,
    'compromiseDate' : IDL.Text,
    'detectionMethod' : IDL.Text,
    'systemName' : IDL.Text,
    'systemType' : IDL.Text,
  });
  const CreateIncidentArgs = IDL.Record({
    'id' : IncidentId,
    'status' : IDL.Text,
    'userAccounts' : IDL.Text,
    'hostnames' : IDL.Text,
    'businessImpact' : IDL.Text,
    'type' : IDL.Text,
    'dataExposed' : IDL.Text,
    'systems' : IDL.Text,
    'timestamp' : Timestamp,
    'affectedSystems' : IDL.Vec(AffectedSystem),
    'severity' : IDL.Text,
    'usersAffected' : IDL.Nat,
    'qrCode' : IDL.Opt(IDL.Text),
  });
  const IncidentView = IDL.Record({
    'id' : IncidentId,
    'status' : IDL.Text,
    'userAccounts' : IDL.Text,
    'hostnames' : IDL.Text,
    'businessImpact' : IDL.Text,
    'type' : IDL.Text,
    'dataExposed' : IDL.Text,
    'systems' : IDL.Text,
    'timestamp' : Timestamp,
    'affectedSystems' : IDL.Vec(AffectedSystem),
    'severity' : IDL.Text,
    'usersAffected' : IDL.Nat,
    'qrCode' : IDL.Opt(IDL.Text),
  });
  const Stats = IDL.Record({
    'avgResponseMinutes' : IDL.Float64,
    'incidentsThisWeek' : IDL.Nat,
    'incidentsToday' : IDL.Nat,
    'criticalAlertCount' : IDL.Nat,
  });
  const AlertView = IDL.Record({
    'id' : AlertId,
    'title' : IDL.Text,
    'incidentId' : IDL.Opt(IncidentId),
    'source' : IDL.Text,
    'falsePositive' : IDL.Bool,
    'description' : IDL.Text,
    'acknowledged' : IDL.Bool,
    'timestamp' : Timestamp,
    'severity' : IDL.Text,
  });
  const IocId = IDL.Text;
  const IOC = IDL.Record({
    'value' : IDL.Text,
    'addedAt' : Timestamp,
    'iocType' : IDL.Text,
    'severity' : IDL.Text,
    'iocId' : IocId,
  });
  const FeedId = IDL.Text;
  const ThreatFeed = IDL.Record({
    'title' : IDL.Text,
    'source' : IDL.Text,
    'feedId' : FeedId,
    'publishedAt' : Timestamp,
    'description' : IDL.Text,
    'severity' : IDL.Text,
  });
  
  return IDL.Service({
    'acknowledgeAlert' : IDL.Func([AlertId], [IDL.Bool], []),
    'createAlert' : IDL.Func([CreateAlertArgs], [], []),
    'createIncident' : IDL.Func([CreateIncidentArgs], [], []),
    'deleteIncident' : IDL.Func([IncidentId], [IDL.Bool], []),
    'getIncident' : IDL.Func([IncidentId], [IDL.Opt(IncidentView)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'linkAlertToIncident' : IDL.Func([AlertId, IncidentId], [IDL.Bool], []),
    'listAlerts' : IDL.Func([], [IDL.Vec(AlertView)], ['query']),
    'listIOCs' : IDL.Func([], [IDL.Vec(IOC)], ['query']),
    'listIncidents' : IDL.Func([], [IDL.Vec(IncidentView)], ['query']),
    'listThreatFeeds' : IDL.Func([], [IDL.Vec(ThreatFeed)], ['query']),
    'markAlertFalsePositive' : IDL.Func([AlertId], [IDL.Bool], []),
    'updateIncidentQrCode' : IDL.Func([IncidentId, IDL.Text], [IDL.Bool], []),
    'updateIncidentStatus' : IDL.Func([IncidentId, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };