/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AffectedSystem {
  'criticality' : string,
  'compromiseDate' : string,
  'detectionMethod' : string,
  'systemName' : string,
  'systemType' : string,
}
export type AlertId = string;
export interface AlertView {
  'id' : AlertId,
  'title' : string,
  'incidentId' : [] | [IncidentId],
  'source' : string,
  'falsePositive' : boolean,
  'description' : string,
  'acknowledged' : boolean,
  'timestamp' : Timestamp,
  'severity' : string,
}
export interface CreateAlertArgs {
  'id' : AlertId,
  'title' : string,
  'source' : string,
  'description' : string,
  'timestamp' : Timestamp,
  'severity' : string,
}
export interface CreateIncidentArgs {
  'id' : IncidentId,
  'status' : string,
  'userAccounts' : string,
  'hostnames' : string,
  'businessImpact' : string,
  'type' : string,
  'dataExposed' : string,
  'systems' : string,
  'timestamp' : Timestamp,
  'affectedSystems' : Array<AffectedSystem>,
  'severity' : string,
  'usersAffected' : bigint,
  'qrCode' : [] | [string],
}
export type FeedId = string;
export interface IOC {
  'value' : string,
  'addedAt' : Timestamp,
  'iocType' : string,
  'severity' : string,
  'iocId' : IocId,
}
export type IncidentId = string;
export interface IncidentView {
  'id' : IncidentId,
  'status' : string,
  'userAccounts' : string,
  'hostnames' : string,
  'businessImpact' : string,
  'type' : string,
  'dataExposed' : string,
  'systems' : string,
  'timestamp' : Timestamp,
  'affectedSystems' : Array<AffectedSystem>,
  'severity' : string,
  'usersAffected' : bigint,
  'qrCode' : [] | [string],
}
export type IocId = string;
export interface Stats {
  'avgResponseMinutes' : number,
  'incidentsThisWeek' : bigint,
  'incidentsToday' : bigint,
  'criticalAlertCount' : bigint,
}
export interface ThreatFeed {
  'title' : string,
  'source' : string,
  'feedId' : FeedId,
  'publishedAt' : Timestamp,
  'description' : string,
  'severity' : string,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'acknowledgeAlert' : ActorMethod<[AlertId], boolean>,
  'createAlert' : ActorMethod<[CreateAlertArgs], undefined>,
  'createIncident' : ActorMethod<[CreateIncidentArgs], undefined>,
  'deleteIncident' : ActorMethod<[IncidentId], boolean>,
  'getIncident' : ActorMethod<[IncidentId], [] | [IncidentView]>,
  'getStats' : ActorMethod<[], Stats>,
  'linkAlertToIncident' : ActorMethod<[AlertId, IncidentId], boolean>,
  'listAlerts' : ActorMethod<[], Array<AlertView>>,
  'listIOCs' : ActorMethod<[], Array<IOC>>,
  'listIncidents' : ActorMethod<[], Array<IncidentView>>,
  'listThreatFeeds' : ActorMethod<[], Array<ThreatFeed>>,
  'markAlertFalsePositive' : ActorMethod<[AlertId], boolean>,
  'updateIncidentQrCode' : ActorMethod<[IncidentId, string], boolean>,
  'updateIncidentStatus' : ActorMethod<[IncidentId, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];