/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AlertView {
    id: AlertId;
    title: string;
    incidentId?: IncidentId;
    source: string;
    falsePositive: boolean;
    description: string;
    acknowledged: boolean;
    timestamp: Timestamp;
    severity: string;
}
export type Timestamp = bigint;
export interface IncidentView {
    id: IncidentId;
    status: string;
    userAccounts: string;
    hostnames: string;
    businessImpact: string;
    type: string;
    dataExposed: string;
    systems: string;
    timestamp: Timestamp;
    affectedSystems: Array<AffectedSystem>;
    severity: string;
    usersAffected: bigint;
    qrCode?: string;
}
export type IncidentId = string;
export interface IOC {
    value: string;
    addedAt: Timestamp;
    iocType: string;
    severity: string;
    iocId: IocId;
}
export interface CreateAlertArgs {
    id: AlertId;
    title: string;
    source: string;
    description: string;
    timestamp: Timestamp;
    severity: string;
}
export type AlertId = string;
export interface ThreatFeed {
    title: string;
    source: string;
    feedId: FeedId;
    publishedAt: Timestamp;
    description: string;
    severity: string;
}
export interface Stats {
    avgResponseMinutes: number;
    incidentsThisWeek: bigint;
    incidentsToday: bigint;
    criticalAlertCount: bigint;
}
export interface AffectedSystem {
    criticality: string;
    compromiseDate: string;
    detectionMethod: string;
    systemName: string;
    systemType: string;
}
export type FeedId = string;
export interface CreateIncidentArgs {
    id: IncidentId;
    status: string;
    userAccounts: string;
    hostnames: string;
    businessImpact: string;
    type: string;
    dataExposed: string;
    systems: string;
    timestamp: Timestamp;
    affectedSystems: Array<AffectedSystem>;
    severity: string;
    usersAffected: bigint;
    qrCode?: string;
}
export type IocId = string;
export interface backendInterface {
    acknowledgeAlert(id: AlertId): Promise<boolean>;
    createAlert(args: CreateAlertArgs): Promise<void>;
    createIncident(args: CreateIncidentArgs): Promise<void>;
    deleteIncident(id: IncidentId): Promise<boolean>;
    getIncident(id: IncidentId): Promise<IncidentView | null>;
    getStats(): Promise<Stats>;
    linkAlertToIncident(alertId: AlertId, incidentId: IncidentId): Promise<boolean>;
    listAlerts(): Promise<Array<AlertView>>;
    listIOCs(): Promise<Array<IOC>>;
    listIncidents(): Promise<Array<IncidentView>>;
    listThreatFeeds(): Promise<Array<ThreatFeed>>;
    markAlertFalsePositive(id: AlertId): Promise<boolean>;
    updateIncidentQrCode(id: IncidentId, qrCode: string): Promise<boolean>;
    updateIncidentStatus(id: IncidentId, newStatus: string): Promise<boolean>;
}
import type { AffectedSystem as _AffectedSystem, AlertId as _AlertId, AlertView as _AlertView, CreateIncidentArgs as _CreateIncidentArgs, IncidentId as _IncidentId, IncidentView as _IncidentView, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acknowledgeAlert(arg0: AlertId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeAlert(arg0);
            return result;
        }
    }
    async createAlert(arg0: CreateAlertArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlert(arg0);
            return result;
        }
    }
    async createIncident(arg0: CreateIncidentArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createIncident(to_candid_CreateIncidentArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIncident(to_candid_CreateIncidentArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteIncident(arg0: IncidentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIncident(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIncident(arg0);
            return result;
        }
    }
    async getIncident(arg0: IncidentId): Promise<IncidentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncident(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncident(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async linkAlertToIncident(arg0: AlertId, arg1: IncidentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.linkAlertToIncident(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkAlertToIncident(arg0, arg1);
            return result;
        }
    }
    async listAlerts(): Promise<Array<AlertView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAlerts();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAlerts();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async listIOCs(): Promise<Array<IOC>> {
        if (this.processError) {
            try {
                const result = await this.actor.listIOCs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listIOCs();
            return result;
        }
    }
    async listIncidents(): Promise<Array<IncidentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listIncidents();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listIncidents();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async listThreatFeeds(): Promise<Array<ThreatFeed>> {
        if (this.processError) {
            try {
                const result = await this.actor.listThreatFeeds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listThreatFeeds();
            return result;
        }
    }
    async markAlertFalsePositive(arg0: AlertId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markAlertFalsePositive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAlertFalsePositive(arg0);
            return result;
        }
    }
    async updateIncidentQrCode(arg0: IncidentId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIncidentQrCode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIncidentQrCode(arg0, arg1);
            return result;
        }
    }
    async updateIncidentStatus(arg0: IncidentId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIncidentStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIncidentStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AlertView_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertView): AlertView {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_IncidentView_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncidentView): IncidentView {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IncidentId]): IncidentId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IncidentView]): IncidentView | null {
    return value.length === 0 ? null : from_candid_IncidentView_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _IncidentId;
    status: string;
    userAccounts: string;
    hostnames: string;
    businessImpact: string;
    type: string;
    dataExposed: string;
    systems: string;
    timestamp: _Timestamp;
    affectedSystems: Array<_AffectedSystem>;
    severity: string;
    usersAffected: bigint;
    qrCode: [] | [string];
}): {
    id: IncidentId;
    status: string;
    userAccounts: string;
    hostnames: string;
    businessImpact: string;
    type: string;
    dataExposed: string;
    systems: string;
    timestamp: Timestamp;
    affectedSystems: Array<AffectedSystem>;
    severity: string;
    usersAffected: bigint;
    qrCode?: string;
} {
    return {
        id: value.id,
        status: value.status,
        userAccounts: value.userAccounts,
        hostnames: value.hostnames,
        businessImpact: value.businessImpact,
        type: value.type,
        dataExposed: value.dataExposed,
        systems: value.systems,
        timestamp: value.timestamp,
        affectedSystems: value.affectedSystems,
        severity: value.severity,
        usersAffected: value.usersAffected,
        qrCode: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.qrCode))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AlertId;
    title: string;
    incidentId: [] | [_IncidentId];
    source: string;
    falsePositive: boolean;
    description: string;
    acknowledged: boolean;
    timestamp: _Timestamp;
    severity: string;
}): {
    id: AlertId;
    title: string;
    incidentId?: IncidentId;
    source: string;
    falsePositive: boolean;
    description: string;
    acknowledged: boolean;
    timestamp: Timestamp;
    severity: string;
} {
    return {
        id: value.id,
        title: value.title,
        incidentId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.incidentId)),
        source: value.source,
        falsePositive: value.falsePositive,
        description: value.description,
        acknowledged: value.acknowledged,
        timestamp: value.timestamp,
        severity: value.severity
    };
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IncidentView>): Array<IncidentView> {
    return value.map((x)=>from_candid_IncidentView_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AlertView>): Array<AlertView> {
    return value.map((x)=>from_candid_AlertView_n8(_uploadFile, _downloadFile, x));
}
function to_candid_CreateIncidentArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateIncidentArgs): _CreateIncidentArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: IncidentId;
    status: string;
    userAccounts: string;
    hostnames: string;
    businessImpact: string;
    type: string;
    dataExposed: string;
    systems: string;
    timestamp: Timestamp;
    affectedSystems: Array<AffectedSystem>;
    severity: string;
    usersAffected: bigint;
    qrCode?: string;
}): {
    id: _IncidentId;
    status: string;
    userAccounts: string;
    hostnames: string;
    businessImpact: string;
    type: string;
    dataExposed: string;
    systems: string;
    timestamp: _Timestamp;
    affectedSystems: Array<_AffectedSystem>;
    severity: string;
    usersAffected: bigint;
    qrCode: [] | [string];
} {
    return {
        id: value.id,
        status: value.status,
        userAccounts: value.userAccounts,
        hostnames: value.hostnames,
        businessImpact: value.businessImpact,
        type: value.type,
        dataExposed: value.dataExposed,
        systems: value.systems,
        timestamp: value.timestamp,
        affectedSystems: value.affectedSystems,
        severity: value.severity,
        usersAffected: value.usersAffected,
        qrCode: value.qrCode ? candid_some(value.qrCode) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
